name: Linter

# Run this workflow every time a new commit pushed to your repository
on: workflow_dispatch

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base
    # Set the type of machine to run on
    runs-on: ubuntu-latest  
    
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - run: git pull
      - run: dotnet tool install -g dotnet-format
      - name: format
        run: dotnet-format -f Assets/ -v d
        working-directory: ${{env.working-directory}}
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[Bot] Automated dotnet-format update"
          add: "*.cs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
